### ISSUE TITLE
OutOfMemoryError on login

### ISSUE THREAD

**Issue by d-o-g** [hawolt/custom-league-client#2]
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3537)
	at java.base/java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:100)
	at java.base/java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:130)
	at java.base/java.io.OutputStream.write(OutputStream.java:127)
	at com.hawolt.rman.RMANFile.extract(RMANFile.java:67)
	at com.hawolt.version.local.LocalSupplierUtility.downloadBundle(LocalSupplierUtility.java:30)
	at com.hawolt.version.local.LocalGameFileVersion.execute(LocalGameFileVersion.java:50)
	at com.hawolt.generic.runnable.ExceptionalRunnable.run(ExceptionalRunnable.java:23)
	at com.hawolt.version.local.LocalGameFileVersion.<init>(LocalGameFileVersion.java:40)
	at com.hawolt.version.local.LocalGameFileVersion.<init>(LocalGameFileVersion.java:33)
	at com.hawolt.virtual.leagueclient.instance.AbstractVirtualLeagueClientInstance.login(AbstractVirtualLeagueClientInstance.java:82)
	at com.hawolt.client.RiotClient.login(RiotClient.java:77)
	at com.hawolt.client.RiotClient.loginAndCreate(RiotClient.java:66)
	at com.hawolt.client.RiotClient.<init>(RiotClient.java:31)
	at com.hawolt.LeagueClientUI.onLogin(LeagueClientUI.java:123)

**Comment by hawolt** [comment]
attempted to improve ram usage on startup by adjusting the rman parser https://github.com/hawolt/league-client-api/commit/7b19a92b8de507c85c6a13c5ca0e955ed88e039a
let me know if you still experience the OutOfMemoryError

**Comment by d-o-g** [comment]
Fixed
