### ISSUE TITLE
[ERROR] com.hawolt.LeagueClientUI::onLoginFlowException Failed to initialize Client: JSONObject["lol.game_client_settings.redge_urls.public"] not found.

### ISSUE THREAD

**Issue by Mreaggle** [hawolt/custom-league-client#65]
[29 Aug 2023 03:38:32] [ERROR] com.hawolt.LeagueClientUI::onLoginFlowException Failed to initialize Client: JSONObject["lol.game_client_settings.redge_urls.public"] not found.

After trying to normally run LeagueClientUI.

**Comment by hawolt** [comment]
already fixed on dev branch, will be included in next release

**Comment by Mreaggle** [comment]
Next release came, but it stills not working, and now, a new error comes:

[01 Sep 2023 02:33:03] [ERROR] com.hawolt.LeagueClientUI::onLoginFlowException Failed to initialize Client: JSONObject["lol.game_client_settings.redge_urls.public"] not found.
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "com.hawolt.ui.MainUI.adjust()" because "this.mainUI" is null
	at com.hawolt.LeagueClientUI.windowStateChanged(LeagueClientUI.java:204)
	at java.desktop/java.awt.Window.processWindowStateEvent(Window.java:2168)
	at java.desktop/java.awt.Window.processEvent(Window.java:2051)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4995)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

Process finished with exit code 0

**Comment by Mreaggle** [comment]
Now I've got only the first error:
[01 Sep 2023 02:35:44] [ERROR] com.hawolt.LeagueClientUI::onLoginFlowException Failed to initialize Client: JSONObject["lol.game_client_settings.redge_urls.public"] not found.

**Comment by hawolt** [comment]
please add the entire log not just the error message and use the issue template, what is the region, do you have 2fa?

**Comment by hawolt** [comment]
this should be resolved on dev branch for all regions
